### ISSUE TITLE
TriggerHandlerComprehensive does not work with custom objects

### ISSUE THREAD

**Issue by RenegadeCoder** [joeferraro/MavensMate-Templates#27]
This template is unable to compile when used with a custom object because the bindings such as ```new{{ object_name }}s``` will resolve to something like ```newCustom_Object__cs``` which is invalid because of the double underscore.

I suggest using more generic variable names here, such as ```newRecords``` instead of the merge expression

**Comment by joeferraro** [comment]
@RenegadeCoder happy to accept a PR, cheers
